# NX Open Python - generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file and the cadnx/ folder to a machine with Siemens NX installed.
#      The easiest layout is:
#          output/
#              this_script.py
#              cadnx/
#   3. Open NX -> File -> Execute -> NX Open -> select this file.
#   4. NX builds the geometry and exports the STEP file.
# ----------------------------------------------------------------------------

import os
import sys

# Ensure cadnx is importable on the NX machine.
# Adjust these paths if cadnx/ is in a different location.
_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
for _candidate in (
    _SCRIPT_DIR,
    os.path.abspath(os.path.join(_SCRIPT_DIR, "..", "skills", "nx-cad")),
):
    if _candidate not in sys.path:
        sys.path.insert(0, _candidate)

from cadnx import NXBuilder


def build(output_path: str = None):
    b = NXBuilder()

    # Parameters
    # Agent defines all named dimensions here, e.g.:
    # length = 100
    # width = 60
    # height = 20

    # Modeling
    # Use NXBuilder calls when they directly match the intended geometry.
    # Use raw NXOpen builders directly when they produce higher-fidelity NX
    # geometry; confirm raw API shapes through MCP API-review mode when
    # available.
    # Agent inserts NXBuilder calls here, e.g.:
    # body = b.box(length, width, height, origin=(0, 0, 0))
    # hole1 = b.hole(8, height + 2, position=(20, 15, height))
    # b.boolean_subtract(body, hole1)
    # b.chamfer(b.get_top_edges(body), offset=2)

    # Export
    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    b.export_step(output_path)


def main():
    default_output = os.path.splitext(os.path.abspath(__file__))[0] + ".step"
    output = sys.argv[1] if len(sys.argv) > 1 else default_output
    build(output)


if __name__ == "__main__":
    main()
