# NX Open Python - raw high-fidelity journal generated by nx-cad skill
# ----------------------------------------------------------------------------
# HOW TO RUN:
#   1. Copy this file to a machine with Siemens NX installed.
#   2. Open NX -> File -> Execute -> NX Open -> select this file.
#   3. NX builds the geometry. If STEP export is enabled, it writes the STEP
#      next to this journal.
# ----------------------------------------------------------------------------

import os
import sys

import NXOpen
import NXOpen.Features


RAW_NXOPEN_HIGH_FIDELITY = True

# Replace this with MCP_API_REVIEW when Designcenter/NXOpen MCP tools were used.
STATIC_ONLY_NXOPEN_REVIEW = {
    "reason": "Designcenter/NXOpen MCP tools were not available in this agent session.",
    "checks": [],
}


def safe_dispose(obj):
    if obj is not None and hasattr(obj, "Dispose"):
        obj.Dispose()


def create_work_part_if_needed(session, part_stem="nx_cad_part"):
    work_part = session.Parts.Work
    if work_part is not None:
        print("Using existing NX work part:", work_part)
        return work_part

    script_dir = os.path.dirname(os.path.abspath(__file__))
    work_dir = os.path.join(script_dir, "_cadnx_work")
    os.makedirs(work_dir, exist_ok=True)
    part_path = os.path.join(work_dir, part_stem)

    result = session.Parts.NewDisplay(part_path, NXOpen.Part.Units.Millimeters)
    load_status = None
    if isinstance(result, tuple):
        new_part = result[0]
        if len(result) > 1:
            load_status = result[1]
    else:
        new_part = result

    safe_dispose(load_status)
    work_part = session.Parts.Work or new_part
    if work_part is None:
        raise RuntimeError("Could not create an NX work part. Open a part and run the journal again.")

    print("Created NX work part:", part_path)
    return work_part


def export_step(session, work_part, output_path):
    if output_path is None:
        output_path = os.path.splitext(os.path.abspath(__file__))[0] + ".step"

    part_path = getattr(work_part, "FullPath", "") or os.path.splitext(output_path)[0] + ".prt"
    step_creator = session.DexManager.CreateStep214Creator()
    try:
        step_creator.InputFile = part_path
        step_creator.OutputFile = output_path
        step_creator.Commit()
        print("Exported STEP:", output_path)
    finally:
        step_creator.Destroy()


def main():
    session = NXOpen.Session.GetSession()
    work_part = create_work_part_if_needed(session)
    session.SetUndoMark(NXOpen.Session.MarkVisibility.Visible, "Create NX CAD Part")

    # Parameters
    # Define independent prompt parameters and derived dimensions here.

    # Modeling
    # Use direct NXOpen builders, curves, sections, expressions, PMI, save, and
    # export APIs. Wrap every Create*Builder object in try/finally Destroy().

    print("Raw NXOpen high-fidelity journal completed for work part:", work_part)


if __name__ == "__main__":
    main()
